name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install buildozer
      - name: Make APK
        run: buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: bin/*.apk
